version: '3.8'

services:
  process_service:
    build: ./process_scheduler
    container_name: process_service
    ports:
      - "5000:5000"

  memory_service:
    build: ./memory_manager
    container_name: memory_service
    ports:
      - "5001:5001"

  api:
    build:
      context: ./multithreading_service  # Pointing to the folder where the Dockerfile is located
    container_name: api
    ports:
      - "8002:8000"
    volumes:
      - ./multithreading_service:/app  # Mount the multithreading_service folder as volume
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=tasksdb

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasksdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
